<?php
//定义数据库常量
define('DBHOST','localhost');
define('DBUSER','root');
define('DBPWD','root');
define('DBPORT','3306');
define('DBCHARSET','utf8');
//表前缀
define('DBPREFIX','pg_');
//主表的前缀
define('PRIMARY_DBPREFIX','bg_');
define('DBNAME','test');
//页面编码
define('CHARSET','utf-8');
